import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <html lang="en">
    <body className={inter.className}>
     <nav style = {{width: "100%"}}>
      <Link href="/articles" style={{marginLeft: "10px"}}>articles</Link>
      <Link href="/posts" style={{marginLeft: "10px"}}>posts</Link>
      <Link href="/" style={{marginLeft: "10px"}}>Home</Link>
     </nav>
     {children}
    </body>
   </html>
  );
}
